# -*- coding: utf-8 -*-
"""Cars Data Set.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rAYYkdnl8l1dT38h3o1OEy5sDhwfM3vJ
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# 1. Load data set using pandas function and print last 5 record. 5

car=pd.read_csv('/content/cars.csv')
car

#2 Print the size and shape of the data frame.
car.size

car.shape

# 3 Find the mean price for each brand using the pandas function.
data=car.groupby(['brand'])['price'].mean()
data

# 4 Count the cars having Black color:
count=car[car['color']=='black'].shape[0]
count

# 5 Find which Brand have maximum car in year 2017.
car_17=car[car['brand']==2017]
car_count_by_brand = car.groupby(['brand'])['brand'].count()
car_count_by_brand.max()

# 6 Create a line chart which shows proportion for each car brand.

proportion_by_brand = car_count_by_brand / car_count_by_brand.sum()

plt.plot(proportion_by_brand.index, proportion_by_brand.values)
plt.xlabel("Brand")
plt.ylabel("Proportion")
plt.show()

# 7 Print the statistical information of the data frame.
car.describe()

#8 Remove all the duplicate values from the data frame:
df=car.drop_duplicates()

df

car.shape

# 9 Count the null values in the database and replace with median value:
count=car.isnull().sum()
count

car['mileage'].fillna(car['mileage'].median(), inplace=True)

car.shape

