# -*- coding: utf-8 -*-
"""diamonds .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cjWzag5qTQllSsH4zhXjRDTEmX2wuAVd
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

diam=pd.read_csv('/content/diamonds.csv')
diam

diam.tail(5)

#Draw the bar chart of costliest and cheapest diamonds:

df_sorted = diam.sort_values(by='price')
costliest_diamond = df_sorted.iloc[-1]
cheapest_diamond = df_sorted.iloc[0]

plt.bar(['Costliest', 'Cheapest'],
        [costliest_diamond['price'],
        cheapest_diamond['price']])
plt.xlabel("Diamond")
plt.ylabel("Price")
plt.show()

plt.xlabel("Diamond")
plt.ylabel("Price")
plt.show()

#3 Draw the chart for Price vs Carat of Diamonds.
diam.plot(x='price',y='carat')
plt.title('Diamonds')
plt.show()

# Print the record where either of dimension (x,y,z) is Zero:
zero=diam[(diam['x']==0)|(diam['y']==0)|(diam['z']==0)]
zero

#5 Create a new data frame by multiplying x, y, z:
xyz=pd.DataFrame({'xyz' : diam['x']* diam['y']*diam['z']})
xyz

#6 Drop all the dimension (X,Y,Z):
diam.drop(['x','y','z'],axis=1)

#7 Print all the Statistical information of the data frame:
diam.describe()

#8 Remove all the duplicate values from the data frame:
diam.drop_duplicates()

#9 Count the null values in the database and replace with mean value:
diam.isnull().count()

diam.fillna(diam.median())

