# -*- coding: utf-8 -*-
"""flight.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U9ex_YOCgdgEIS8h7WrD7FMn5_DxmxXB
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

flight=pd.read_csv('/content/flight.csv')
flight

#1. Load data set using pandas function and print last 5 records.
flight.tail(5)

# 2. Print the number of flights from one point to another.
print(flight.groupby(['origin', 'dest'])['flight'].count())

# 3. Find the best airline in terms of departure.
print(flight.groupby('sched_arr_time')['arr_delay'].mean().min())

# 4. Create new column speed by calculating speed of airplane using distance and time taken to travel.
flight['time_hour'] = (flight['distance'] / (flight['air_time']/60))
print(flight[['distance', 'air_time', 'time_hour']].head())

# 5. Create a data frame containing total number of flights going to a particular destination.
total=flight.groupby('dest')['flight'].count().reset_index()
total

# 6. Find the size and shape of the data set.
flight.size

flight.shape

# 7. Print all the column header of the data frame.
flight.columns

# 8. Remove all the duplicate values from the data frame.
flight.drop_duplicates()

# 9. Count the null values in the database and replace with mean value.
flight.isnull().sum()

flight.fillna(flight.mean(),inplace=True)

flight.isnull().sum()

