# -*- coding: utf-8 -*-
"""Iris Data Set.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lpANNI68vnyNiaWqP5SOGNk6EXr3Nrvc
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Load data set using pandas function and print first 4 record.
iris=pd.read_csv('/content/iris.csv')
iris

iris.head(4)

#Print information of data set.
iris.info

#3 Count the values of each class of species.
iris.value_counts()

# 4. Draw a line chart for sepal-length vs sepal-width.
iris.plot(x='sepal.length',y='sepal.width')
plt.show()

#5 Print shape and size of the data frame.
iris.shape

iris.size

# 6. Print all the column header of the data frame.
print(iris.columns)

# 7. Filter the record from index no 80 to 100.
print(iris.iloc[80:101])

# 8. Remove all the duplicate values from the data frame
iris.drop_duplicates(inplace=True)

iris.drop_duplicates

# 9. Count the null values in the database and replace with median value
iris.isnull().sum()

iris.fillna(iris.median())

iris.isnull().sum()

