# -*- coding: utf-8 -*-
"""movie.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bfwEzVOmKeYcyDtFOLWB88FJSv-WVUUp
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt



data= pd.read_csv('/content/Movie-Data.csv')
data

# Task 1: Print top 10 records

data.head(10)

# Task 2: Movie that earned the most and least profit
data.max

data.min

# Task 3: Print movies with budget or revenue 0
#zero_budget = data[data['Revenue (Millions)'] == 0]
#zero_budget
zero_revenue = data[data['Revenue (Millions)'] == 0]
zero_revenue



# Task 4: Calculate total profits by year
profits_by_year= data.groupby('Year').sum()
profits_by_year

# Task 5: Draw a line chart for runtime of movies
plt.plot(data['Runtime (Minutes)'])
plt.title("Runtime of Movies")
plt.xlabel("Movie")
plt.ylabel("Runtime (Minutes)")
plt.show()

# Task 6: Year with the most movies making profits
year_with_most_profitable_movies = data.groupby('Year').size().max()
year_with_most_profitable_movies

# Task 7: Print size and shape of the data set
data.size

data.shape

# Task 8: Remove duplicate records
data.drop_duplicates()

# Task 9: Count null values and fill with average
data.isnull().sum()

data.fillna(data.mean(), inplace=True)

